import Head from "next/head";
import TestModals from "../components/TestModals";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Modals In NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <TestModals />
    </div>
  );
}
